### ISSUE TITLE
.so file causes Cutter to crash

### ISSUE THREAD

**Issue by VegaDeftwing** [rizinorg/cutter#2862]
**Environment information**
* Operating System: Arch Linux 5.15.10-zen1-1-zen
* Cutter version: 2.0.4
* Obtained from:
  - [] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: .so

**Describe the bug**

Upon loading this .so file, Cutter crashes and displays a window "Cutter received a signal it can't handle and will close. Would you like to create a crash dump for a bug report" 

**To Reproduce**

1. Open Cutter
2. Load the provided .so file
3. Click analyze
4. Crash

**Expected behavior**

Not crashing

**Additional context**

Provided .so file is from https://github.com/VegaDeftwing/PinkTromboneVCV 

zip contains the crash dump file as well as the .so: [CutterBug.zip](https://github.com/rizinorg/cutter/files/7750560/CutterBug.zip)

**Comment by ret2libc** [comment]
Seems to be a problem within Rizin, caused by an infinite recursion due to the types refactoring:
```
#80540 0x00007ffff603fa6b in type_to_format_pair (typedb=0xf46650, format=0x186fc70, fields=0x19235a0, identifier=0x0, type=0x7fff9cecd3f0) at ../librz/type/format.c:3023                    
#80541 0x00007ffff603f562 in base_type_to_format_unfold (typedb=0xf46650, type=0x7fff9cec6740, format=0x186fc70, fields=0x19235a0, identifier=0x0) at ../librz/type/format.c:2910             
#80542 0x00007ffff603fa6b in type_to_format_pair (typedb=0xf46650, format=0x186fc70, fields=0x19235a0, identifier=0x0, type=0x7fff9cecd3f0) at ../librz/type/format.c:3023                    
#80543 0x00007ffff603f562 in base_type_to_format_unfold (typedb=0xf46650, type=0x7fff9cec6740, format=0x186fc70, fields=0x19235a0, identifier=0x0) at ../librz/type/format.c:2910             
#80544 0x00007ffff603f664 in rz_base_type_as_format (typedb=0xf46650, type=0x7fff9cec6740) at ../librz/type/format.c:2934                                                                     
#80545 0x00007ffff603f751 in rz_type_format (typedb=0xf46650, name=0x7fff9cec28a0 "const_reference") at ../librz/type/format.c:2959                                                           
#80546 0x00000000005183a3 in CutterCore::getBaseType(RzBaseTypeKind, char const*) (this=0x98a960 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>, kind=RZ_BASE_TYPE_KIN
D_TYPEDEF, category=0x78bd53 "Typedef") at /home/rschiron/projects/rizinorg/cutter/src/core/Cutter.cpp:3585                                                                                   
#80547 0x00000000005185b1 in CutterCore::getAllTypedefs() (this=0x98a960 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>) at /home/rschiron/projects/rizinorg/cutter/sr
c/core/Cutter.cpp:3616                                                                                                                                                                        
#80548 0x0000000000518212 in CutterCore::getAllTypes() (this=0x98a960 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>) at /home/rschiron/projects/rizinorg/cutter/src/c
ore/Cutter.cpp:3566                                                                                                                                                                           
#80549 0x0000000000671680 in TypesWidget::refreshTypes() (this=0x1560de0) at /home/rschiron/projects/rizinorg/cutter/src/widgets/TypesWidget.cpp:199                                          
#80550 0x00000000006755ce in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (TypesWidget::*)()>::call(void (TypesWidget::*)(), TypesWidget*, void**) (f=(void 
(TypesWidget::*)(class TypesWidget * const)) 0x67164c <TypesWidget::refreshTypes()>, o=0x1560de0, arg=0x7fffffffc3a0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:152     
```

@XVilka will likely work on a fix for this on Rizin side.
